# Generated by Django 4.0.4 on 2022-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverablesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='uuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
