# Generated by Django 4.0.4 on 2022-05-11 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverablesApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('expected_duration', models.IntegerField(blank=True, null=True)),
                ('expected_effort', models.IntegerField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('effort_completed', models.DateField(blank=True, null=True)),
                ('actual_effort', models.DateField(blank=True, null=True)),
                ('percent_complete', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deliverable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverablesApp.deliverables')),
            ],
            options={
                'db_table': 'TASKS',
            },
        ),
    ]
