# Generated by Django 4.0.4 on 2022-05-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksApp', '0003_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'DEPENDENT_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Task_Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_task_id', models.IntegerField(null=True)),
                ('dependent_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasksApp.dependent_type')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasksApp.tasks')),
            ],
            options={
                'db_table': 'TASK_DEPENDENCY',
            },
        ),
    ]
