# Generated by Django 4.0.4 on 2022-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'IMPACT',
            },
        ),
    ]
