# Generated by Django 4.0.4 on 2022-05-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionitemsApp', '0002_alter_actionitems_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='status',
            new_name='status_id',
        ),
    ]
