# Generated by Django 4.0.4 on 2022-05-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='priority',
            new_name='priority_id',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='serverity',
            new_name='serverity_id',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='status',
            new_name='status_id',
        ),
    ]
