# Generated by Django 4.0.4 on 2022-05-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuesApp', '0005_alter_issues_priority_id_alter_issues_serverity_id_and_more'),
        ('decisionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisions',
            name='issue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuesApp.issues'),
        ),
    ]
