# Generated by Django 4.0.4 on 2022-05-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisionsApp', '0002_alter_decisions_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisions',
            old_name='decision_maker',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='decisions',
            old_name='priority',
            new_name='priority_id',
        ),
        migrations.RenameField(
            model_name='decisions',
            old_name='serverity',
            new_name='serverity_id',
        ),
    ]
