# Generated by Django 4.0.4 on 2022-05-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impact'),
        ('decisionsApp', '0003_rename_decision_maker_decisions_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisions',
            name='serverity_id',
        ),
        migrations.AddField(
            model_name='decisions',
            name='date_made',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisions',
            name='impact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.impact'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisions',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
        migrations.AddField(
            model_name='decisions',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
